Book detail 3 structure
wolox-training/fm-angularjs pull request #3
Opened 2021-04-14 17:57 UTC by FedeMacias

## Summary
- Added a border with shadow to the outer container
- Added a green border below the book title
- Fixed the margins to match the requested 

## Screenshot
![Book-description-3-structure](https://user-images.githubusercontent.com/28579312/114757015-baed3c00-9d31-11eb-9496-6bae112a6701.gif)

## Trello Card
https://trello.com/c/tdcye37k/28-detalle-de-libro-iii-estructura

2021-04-19 13:56 UTC, MMarussi commented on scss/detail.scss
> +    .title-border{
This border can be defined in the `.title` class, did you try it?

2021-04-21 16:18 UTC, MMarussi requested changes

2021-04-21 16:18 UTC, MMarussi commented on scss/detail.scss
> +    height: 416px;
Check the indentation in this line

2021-04-21 16:18 UTC, MMarussi commented on scss/detail.scss
> +      border-color: $earls-green;
Have you tried with `border-bottom: 4px solid $earls-green` ?

2021-04-21 16:18 UTC, MMarussi commented on scss/detail.scss
> +      flex-direction: row;
You can remove this rule since it's the default of flex

2021-04-21 16:24 UTC, MMarussi approved these changes

2021-04-23 14:54 UTC, mcallegari10 approved these changes

2021-04-23 14:58 UTC, merged